### PR TITLE
Prevent -ref to be assigned to the -req before an -end-req.

### PR DESCRIPTION
**Pull request by HenriGEIST**
I have add this to prevent references which are between two requirement to be assigned to the preceding requirement.
In my specific case it is because I cover my test with test results in TAP format (Test Anything Protocol).
And I only want the lines containing "ok" result to be used as a covering requirement and not the line containing "not ok" witch I use as an -end-req pattern.
Like this :
  -req        "^ok.*[0-9]+"
  -end-req "^not ok"

Best regards.

### CODE REVIEW

**Comment by goeb** [comment]
Doesn't your modification break the original way for associating references to requirements?(references after a requirement are associated to this requirement)

Have you run the tests (make check)? Do all pass?

Please give an example of your needs: example of test result (input file of reqflow), examples of what you consider a requirement and a reference, example of expected output.

**Comment by HenriGEIST** [comment]
Hello,
Thank you for your attention to the pull request.

I do not think my modification break the original way of associating references to requirement.
But I may not have thought to everything.
It is just to stop associating reference which are not inside of a requirement to the preceeding requirement. Which I think is a bug.

Yes I have run the tests (make check) ?
There is no difference between the result in my branch and your branch.
But 3 test failed in both cases.
See below the test-suite.log content:
`
========================================
   Reqflow 1.6.0: test/test-suite.log
========================================

# TOTAL: 13
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: req-stat-stdin
====================

cp: './SPEC.docx' et './SPEC.docx' identifient le même fichier
FAIL req-stat-stdin.test (exit status: 1)

FAIL: t_second_doc
==================

cp: './SPEC.docx' et './SPEC.docx' identifient le même fichier
FAIL t_second_doc (exit status: 1)

FAIL: t_end_req
===============

cp: './SPEC.docx' et './SPEC.docx' identifient le même fichier
FAIL t_end_req (exit status: 1)
`

For a very simplified example of my needs see below:
conf.req
`
document TEST_LIST        \
   -path test_list.lst    \
   -req "^(Test_.+)"      \
   -sort alphanum

document TEST_RESULT      \
   -path test_result.tap  \
   -req "^ok.*[0-9]+"     \
   -end-req "^not ok"     \
   -ref "(Test_[^ ]*)"    \
   -sort alphanum         \
   -nocov
`
test_list.lst
`
Test_Fc_1_1
Test_Fp_1_1
Test_Fp_1_2
Test_Fp_1_3
Test_Fp_1_4
Test_Fc_3
Test_Fc_4_1
Test_Fc_4_2
Test_Fc_5
Test_Fc_1_2
Test_Fc_2
`
test_result.tap
`
1..11
ok       1 - Test_Fc_1_1
ok       2 - Test_Fp_1_1
not ok   3 - Test_Fp_1_2 # TODO implement this test.
ok       4 - Test_Fp_1_3
ok       5 - Test_Fp_1_4
ok       6 - Test_Fc_3
not ok   7 - Test_Fc_4_1 # TODO implement this test.
ok       8 - Test_Fc_4_2
ok       9 - Test_Fc_5
ok      10 - Test_Fc_1_2
ok      11 - Test_Fc_2
`
What I expect is to have each tests of my test list seen as covered if it is referenced by an "ok" in my test result and beeing ignored if it is referenced by a "not ok".
As I have set -end-req "^not ok" I do not expect the Test_Fc_4_1 for example to be concidered referenced by the preceding "requirement" "ok   6".

Best regards.

**Comment by HenriGEIST** [comment]
Sorry I do not now why github has put some part of my comment in *BOLD* it was not my intent.

**Comment by goeb** [comment]
About the failing tests, I will have a look later (they all pass on my computer).

I feel that you are trying to use reqflow beyond the use for which it was originally designed.

Anyway, without your patch, you could do either of these 2 solutions, that may suit your need.
 
**Solution 1:** Collect only tests that are OK, and attach them to a single requirement, being the first line "1..11"
conf.req:
```
...
document TEST_RESULT
-path test_result.tap
-req "^1\.\..*"
-ref "^ok.* - (Test_[^ ]*)"
-sort alphanum
-nocov
```
Result :
```
$ reqflow trac TEST_LIST
Test_Fc_1_1                                        1..11                                             
Test_Fc_1_2                                        1..11                                             
Test_Fc_2                                          1..11                                             
Test_Fc_3                                          1..11                                             
Test_Fc_4_1                                       
Test_Fc_4_2                                        1..11                                             
Test_Fc_5                                          1..11                                             
Test_Fp_1_1                                        1..11                                             
Test_Fp_1_2                                       
Test_Fp_1_3                                        1..11                                             
Test_Fp_1_4                                        1..11                                             

$ reqflow stat TEST_LIST
U Test_Fc_4_1
U Test_Fp_1_2
```

**Solution 2:** Collect all Test* and attach them to a test result.
Example:
conf.req:
```
...
document TEST_RESULT
-path test_result.tap
-req ".*ok.*-"
-ref "Test_[^ ]*"
-sort alphanum
-nocov
```
Result:
```
$ reqflow trac TEST_LIST
Test_Fc_1_1                                        ok 1 -                                            
Test_Fc_1_2                                        ok 10 -                                           
Test_Fc_2                                          ok 11 -                                           
Test_Fc_3                                          ok 6 -                                            
Test_Fc_4_1                                        not ok 7 -                                        
Test_Fc_4_2                                        ok 8 -                                            
Test_Fc_5                                          ok 9 -                                            
Test_Fp_1_1                                        ok 2 -                                            
Test_Fp_1_2                                        not ok 3 -                                        
Test_Fp_1_3                                        ok 4 -                                            
Test_Fp_1_4                                        ok 5 -                                            
```

**Comment by HenriGEIST** [comment]
Hello,

Sorry for the delay of my reply.

First of all about the failing tests if it can help you to diagnose what happened.
My system is a linux devuan 2.0.
And the exact command I have executed are:
```
git clone https://github.com/goeb/reqflow.git
cd reqflow
./configure
make
make check
```

And the complete result was:
```
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ZIP... yes
checking for XML... yes
checking for POPPLER... yes
checking for PCRE... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for inline... inline
checking for mode_t... yes
checking for size_t... yes
checking for gettimeofday... yes
checking for localtime... yes
checking for regcomp... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strerror... yes
checking for strstr... yes
checking for strtoul... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating test/Makefile
config.status: creating test/envtest
config.status: creating reqflow.iss
config.status: creating src/config.h
config.status: executing depfiles commands
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/Naugrim/reqflow4/reqflow/missing aclocal-1.15 
 cd . && /bin/bash /home/Naugrim/reqflow4/reqflow/missing automake-1.15 --gnu
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/Naugrim/reqflow4/reqflow/missing autoconf
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create --no-recursion
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ZIP... yes
checking for XML... yes
checking for POPPLER... yes
checking for PCRE... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for inline... inline
checking for mode_t... yes
checking for size_t... yes
checking for gettimeofday... yes
checking for localtime... yes
checking for regcomp... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strerror... yes
checking for strstr... yes
checking for strtoul... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
 /bin/bash ./config.status
config.status: creating Makefile
config.status: creating test/Makefile
config.status: creating test/envtest
config.status: creating reqflow.iss
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands
Making all in test
make[1] : on entre dans le répertoire « /home/Naugrim/reqflow4/reqflow/test »
make[1]: rien à faire pour « all ».
make[1] : on quitte le répertoire « /home/Naugrim/reqflow4/reqflow/test »
make[1] : on entre dans le répertoire « /home/Naugrim/reqflow4/reqflow »
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/poppler/cpp -I/usr/include/poppler   -Wall    -g -O2 -MT src/reqflow-main.o -MD -MP -MF src/.deps/reqflow-main.Tpo -c -o src/reqflow-main.o `test -f 'src/main.cpp' || echo './'`src/main.cpp
mv -f src/.deps/reqflow-main.Tpo src/.deps/reqflow-main.Po
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/poppler/cpp -I/usr/include/poppler   -Wall    -g -O2 -MT src/reqflow-logging.o -MD -MP -MF src/.deps/reqflow-logging.Tpo -c -o src/reqflow-logging.o `test -f 'src/logging.cpp' || echo './'`src/logging.cpp
mv -f src/.deps/reqflow-logging.Tpo src/.deps/reqflow-logging.Po
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/poppler/cpp -I/usr/include/poppler   -Wall    -g -O2 -MT src/reqflow-dateTools.o -MD -MP -MF src/.deps/reqflow-dateTools.Tpo -c -o src/reqflow-dateTools.o `test -f 'src/dateTools.cpp' || echo './'`src/dateTools.cpp
mv -f src/.deps/reqflow-dateTools.Tpo src/.deps/reqflow-dateTools.Po
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/poppler/cpp -I/usr/include/poppler   -Wall    -g -O2 -MT src/reqflow-parseConfig.o -MD -MP -MF src/.deps/reqflow-parseConfig.Tpo -c -o src/reqflow-parseConfig.o `test -f 'src/parseConfig.cpp' || echo './'`src/parseConfig.cpp
mv -f src/.deps/reqflow-parseConfig.Tpo src/.deps/reqflow-parseConfig.Po
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/poppler/cpp -I/usr/include/poppler   -Wall    -g -O2 -MT src/reqflow-req.o -MD -MP -MF src/.deps/reqflow-req.Tpo -c -o src/reqflow-req.o `test -f 'src/req.cpp' || echo './'`src/req.cpp
mv -f src/.deps/reqflow-req.Tpo src/.deps/reqflow-req.Po
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/poppler/cpp -I/usr/include/poppler   -Wall    -g -O2 -MT src/reqflow-ReqDocumentTxt.o -MD -MP -MF src/.deps/reqflow-ReqDocumentTxt.Tpo -c -o src/reqflow-ReqDocumentTxt.o `test -f 'src/ReqDocumentTxt.cpp' || echo './'`src/ReqDocumentTxt.cpp
mv -f src/.deps/reqflow-ReqDocumentTxt.Tpo src/.deps/reqflow-ReqDocumentTxt.Po
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/poppler/cpp -I/usr/include/poppler   -Wall    -g -O2 -MT src/reqflow-ReqDocumentDocx.o -MD -MP -MF src/.deps/reqflow-ReqDocumentDocx.Tpo -c -o src/reqflow-ReqDocumentDocx.o `test -f 'src/ReqDocumentDocx.cpp' || echo './'`src/ReqDocumentDocx.cpp
mv -f src/.deps/reqflow-ReqDocumentDocx.Tpo src/.deps/reqflow-ReqDocumentDocx.Po
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/poppler/cpp -I/usr/include/poppler   -Wall    -g -O2 -MT src/reqflow-ReqDocumentHtml.o -MD -MP -MF src/.deps/reqflow-ReqDocumentHtml.Tpo -c -o src/reqflow-ReqDocumentHtml.o `test -f 'src/ReqDocumentHtml.cpp' || echo './'`src/ReqDocumentHtml.cpp
mv -f src/.deps/reqflow-ReqDocumentHtml.Tpo src/.deps/reqflow-ReqDocumentHtml.Po
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/poppler/cpp -I/usr/include/poppler   -Wall    -g -O2 -MT src/reqflow-stringTools.o -MD -MP -MF src/.deps/reqflow-stringTools.Tpo -c -o src/reqflow-stringTools.o `test -f 'src/stringTools.cpp' || echo './'`src/stringTools.cpp
mv -f src/.deps/reqflow-stringTools.Tpo src/.deps/reqflow-stringTools.Po
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/poppler/cpp -I/usr/include/poppler   -Wall    -g -O2 -MT src/reqflow-renderingHtml.o -MD -MP -MF src/.deps/reqflow-renderingHtml.Tpo -c -o src/reqflow-renderingHtml.o `test -f 'src/renderingHtml.cpp' || echo './'`src/renderingHtml.cpp
mv -f src/.deps/reqflow-renderingHtml.Tpo src/.deps/reqflow-renderingHtml.Po
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/poppler/cpp -I/usr/include/poppler   -Wall    -g -O2 -MT src/reqflow-ReqDocumentPdf.o -MD -MP -MF src/.deps/reqflow-ReqDocumentPdf.Tpo -c -o src/reqflow-ReqDocumentPdf.o `test -f 'src/ReqDocumentPdf.cpp' || echo './'`src/ReqDocumentPdf.cpp
mv -f src/.deps/reqflow-ReqDocumentPdf.Tpo src/.deps/reqflow-ReqDocumentPdf.Po
g++ -Wall    -g -O2    -o reqflow src/reqflow-main.o src/reqflow-logging.o src/reqflow-dateTools.o src/reqflow-parseConfig.o src/reqflow-req.o src/reqflow-ReqDocumentTxt.o src/reqflow-ReqDocumentDocx.o src/reqflow-ReqDocumentHtml.o src/reqflow-stringTools.o src/reqflow-renderingHtml.o src/reqflow-ReqDocumentPdf.o -lzip -lz -lxml2 -lpoppler-cpp -lpcreposix 
g++ -DHAVE_CONFIG_H -I. -I./src  -I/usr/include/poppler/cpp -I/usr/include/poppler  -Wall    -g -O2 -MT src/main_pdf-main_pdf.o -MD -MP -MF src/.deps/main_pdf-main_pdf.Tpo -c -o src/main_pdf-main_pdf.o `test -f 'src/main_pdf.cpp' || echo './'`src/main_pdf.cpp
mv -f src/.deps/main_pdf-main_pdf.Tpo src/.deps/main_pdf-main_pdf.Po
g++ -Wall    -g -O2    -o main_pdf src/main_pdf-main_pdf.o -lpoppler-cpp 
gcc -DHAVE_CONFIG_H -I. -I./src    -Wall    -g -O2 -MT src/main_regex-main_regex.o -MD -MP -MF src/.deps/main_regex-main_regex.Tpo -c -o src/main_regex-main_regex.o `test -f 'src/main_regex.c' || echo './'`src/main_regex.c
mv -f src/.deps/main_regex-main_regex.Tpo src/.deps/main_regex-main_regex.Po
gcc -Wall    -g -O2    -o main_regex src/main_regex-main_regex.o -lpcreposix 
gcc -DHAVE_CONFIG_H -I. -I./src  -I/usr/lib/x86_64-linux-gnu/libzip/include  -Wall    -g -O2 -MT src/main_unzip-main_unzip.o -MD -MP -MF src/.deps/main_unzip-main_unzip.Tpo -c -o src/main_unzip-main_unzip.o `test -f 'src/main_unzip.c' || echo './'`src/main_unzip.c
mv -f src/.deps/main_unzip-main_unzip.Tpo src/.deps/main_unzip-main_unzip.Po
gcc -Wall    -g -O2    -o main_unzip src/main_unzip-main_unzip.o -lzip -lz 
gcc -DHAVE_CONFIG_H -I. -I./src  -I/usr/include/libxml2  -Wall    -g -O2 -MT src/main_xml-main_xml.o -MD -MP -MF src/.deps/main_xml-main_xml.Tpo -c -o src/main_xml-main_xml.o `test -f 'src/main_xml.c' || echo './'`src/main_xml.c
mv -f src/.deps/main_xml-main_xml.Tpo src/.deps/main_xml-main_xml.Po
gcc -Wall    -g -O2    -o main_xml src/main_xml-main_xml.o -lxml2 
g++ -DHAVE_CONFIG_H -I. -I./src    -Wall    -g -O2 -MT src/main_testStringCompare-main_testStringCompare.o -MD -MP -MF src/.deps/main_testStringCompare-main_testStringCompare.Tpo -c -o src/main_testStringCompare-main_testStringCompare.o `test -f 'src/main_testStringCompare.cpp' || echo './'`src/main_testStringCompare.cpp
mv -f src/.deps/main_testStringCompare-main_testStringCompare.Tpo src/.deps/main_testStringCompare-main_testStringCompare.Po
g++ -DHAVE_CONFIG_H -I. -I./src    -Wall    -g -O2 -MT src/main_testStringCompare-stringTools.o -MD -MP -MF src/.deps/main_testStringCompare-stringTools.Tpo -c -o src/main_testStringCompare-stringTools.o `test -f 'src/stringTools.cpp' || echo './'`src/stringTools.cpp
mv -f src/.deps/main_testStringCompare-stringTools.Tpo src/.deps/main_testStringCompare-stringTools.Po
g++ -Wall    -g -O2    -o main_testStringCompare src/main_testStringCompare-main_testStringCompare.o src/main_testStringCompare-stringTools.o -lpcreposix 
make[1] : on quitte le répertoire « /home/Naugrim/reqflow4/reqflow »
Making check in test
make[1] : on entre dans le répertoire « /home/Naugrim/reqflow4/reqflow/test »
make  check-TESTS
make[2] : on entre dans le répertoire « /home/Naugrim/reqflow4/reqflow/test »
make[3] : on entre dans le répertoire « /home/Naugrim/reqflow4/reqflow/test »
PASS: req-trac.test
PASS: req-stat.test
FAIL: req-stat-stdin.test
PASS: req-trac-pdf.test
PASS: req-trac-html.test
PASS: req-stat-html2.test
PASS: req-stat-docx-rm.test
PASS: req-same-line.test
PASS: req-stat-sort.test
PASS: SPEC-with-table.test
FAIL: t_second_doc
FAIL: t_end_req
PASS: t_multi_doc
============================================================================
Testsuite summary for Reqflow 1.6.0
============================================================================
# TOTAL: 13
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0
============================================================================
See test/test-suite.log
============================================================================
Makefile:521 : la recette pour la cible « test-suite.log » a échouée
make[3] : on quitte le répertoire « /home/Naugrim/reqflow4/reqflow/test »
Makefile:627 : la recette pour la cible « check-TESTS » a échouée
make[2] : on quitte le répertoire « /home/Naugrim/reqflow4/reqflow/test »
Makefile:717 : la recette pour la cible « check-am » a échouée
make[1] : on quitte le répertoire « /home/Naugrim/reqflow4/reqflow/test »
Makefile:969 : la recette pour la cible « check-recursive » a échouée
```

Secondly about what I am trying to achieve.
I do not know if what I am doing is beyond the use for which reqflow was originally designed.
As I do not know any precise description of this use.
But anyway hacking is by definition using the tools beyond the use for which they are originally designed.
What I am doing exactly is:
1. Writing some specs in asciidoc format with specs `Id`.
2. Writing the corresponding tests in different languages (C, Ada, sh, ...) in functions named `Test_Id`.
3. Writing the code hopping it pass the tests.
4. Execute the tests which generate tests reports in Test Anything Protocol referencing the `Test_Id`.

My goal is to have a complete traceability from specs to test results.

Then I expect reqflow to:
1. Trace all requirements covered by a test function.
2. Trace all test functions covered by a test result reporting a success.
When the test result report a failure I do not want to count it as covering the corresponding test function. As in fact the failure indicate that the requirement is still not covered.

In this respect the two solution you proposed does not fully fit my needs.

- The solution 2 will clearly count the failing test as covering their requirements. But as failures they clearly do not cover anything. 
- The solution 1 is really near to my need but it loose the tests results covering the tests and attribute all the covering to the complete test suite not to the individual tests.

Best regards.

**Comment by goeb** [comment]
I fixed the make check.

**Comment by goeb** [comment]
I am still not sure I understand your point. What would you like `reqflow trac TEST_LIST` print?

**Comment by HenriGEIST** [comment]
Thanks for the fix. I have merged it in my branch and now I get every test of the `make chekc` to PASS.

What I expect of the `reqflow trac TEST_LIST` is exactly what I get with my modification.
```
Requirements of TEST_LIST                          Requirements Downstream                           
--------------------------------------------------------------------------------------------------------------------
Test_Fc_1_1                                        ok 1                                              
Test_Fc_1_2                                        ok 10                                             
Test_Fc_2                                          ok 11                                             
Test_Fc_3                                          ok 6                                              
Test_Fc_4_1                                       
Test_Fc_4_2                                        ok 8                                              
Test_Fc_5                                          ok 9                                              
Test_Fp_1_1                                        ok 2                                              
Test_Fp_1_2                                       
Test_Fp_1_3                                        ok 4                                              
Test_Fp_1_4                                        ok 5
```
In my point of view any reference between an `-end-req` and the next `-req` must be ignored just like any reference before the `-start-after` or after the `-stop-after`.
reference should only be captured inside a requirement text.

Best regards.

**Comment by goeb** [comment]
I understand your point now, and your patch.
However `-end-req` is intended for capturing the text of the requirement. Let's take a example:
```
PRINTF_01
printf -help shall display a help message and exit.
#endtext
Ref: SYS_155

PRINTF_02
The FORMAT parameter shall control the output as in C printf.
#endtext
```
The `-end-req #endtext` could be used here to tell where the text of the requirement ends.
Maybe I should add a test for this case.

Back to your need, you could achieve what you want like this:
```
document TEST_RESULT
	-path test_result.tap
	-req "^ok.[0-9]+"
	-end-req "^not ok"
	-ref "^ok.*(Test_[^ ]*)"
	-sort alphanum
	-nocov
```
Here, the `-ref` parameter forces lines starting by `ok`, and the parentheses indicate which part is the actual reference.

**Comment by HenriGEIST** [comment]
Hello,
Thanks for your solution it does not seem general to my eyes as it only work if all refs are one the same line as the requirement. But at least it work well in all my particular use case for the moment.

There is still some thing which I do not understand in your example.
If I read well you are using the toke `#endtext` to avoid having the reference append to the text of the requirement when you use the command `reqflow review`.
But `reqflow` already remove the references from the requirement text without using it.
Then what is really the point ?

Just for curiosity, have you got some specs for reqflow itself that can be tracked by reqflow ?

**Comment by goeb** [comment]
To explain the `#endtext` example, let's consider this other example:

```
PRINTF_02
The FORMAT parameter shall control the output as in C printf.
#endtext
Example:
    $ printf %08d 1234
    00001234
```
The example after the `#endtext` is not part of the requirement. But it illustrates the subject.

> Just for curiosity, have you got some specs for reqflow itself that can be tracked by reqflow ?

No there isn't any.

**Comment by HenriGEIST** [comment]
OK Thanks for all.
I think for the moment I can close the pull request.

**Pull request closed without merging**
